### ISSUE TITLE
Поправить env файл в update-buildx-cache

### ISSUE THREAD

**Issue by birthdaysgift** [week-password/wlss-backend#57]
Во время работы над добавлением кэша докера в CI, мы добавили экшн `.github/actions/docker/update-buildx-cache/action.yml`, который должен обновлять кеш докера. Но в нём была допущена ошибка - в этом экшене был захардкожен путь до `.env` файла, из которого берутся переменные для получения доступа к локальному кэшу.
```yaml
runs:
  using: composite
  steps:
    - name: Update buildx cache
      shell: bash
      run: |
        set -o allexport; source envs/ci/lint/.env; set +o allexport;  # export environment variables from dotenv file
#          проблема здесь ^^^^^^^^^^^^^^^^^^^^^^^^^
        rm -rf ${BUILDX_CACHE_SRC}
        mv ${BUILDX_CACHE_DEST} ${BUILDX_CACHE_SRC}
```

Так как этот экшн используется не только для CI с линтерами, но и для CI с тестами. То для CI с тестами там должен быть другой путь - `envs/ci/test/.env`.

Эта проблема блокирует задачу #55.

В рамках этой задачи необходимо прокинуть переменную окружения с путём до `.env` файла в экшн и использовать её вместо захардкоженого пути.
